# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef951293ba3aed7cd399cb82834404f5be14e46817192e5219e550a15a62e58c6c7aa0f6eb364e99e03366e753c4182db569baf978114c81cdd6bbcc8e5e2587

test:
  secret_key_base: 94d109b9a68ae5779d0a7c95848386b18c52b676e0e7fa22c53eff5641f0bf7f9d8e7e4cda67a1baf74f70099f067008e1ac62f27d941a4d7a64863f339670d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
